apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: test2-feb5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test2-feb5
  name: test2-feb5
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
